export { Notes } from './notes/notes.component'
export { Modal } from './modal/modal.component'
export { Canvas } from './canvas/canvas.component'
export { GameOver } from './game-over/game-over.component'
export { Background } from './background/backgound.component'
export { Instructions } from './instructions/instructions.component'
